/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalendarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/views/calendar-view.ts
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var WEEKDAY_VISIBILITY_KEYS = [
  "showSunday",
  "showMonday",
  "showTuesday",
  "showWednesday",
  "showThursday",
  "showFriday",
  "showSaturday"
];
var DEFAULT_SETTINGS = {
  showDashes: true,
  enableDailyNoteOnDoubleTap: true,
  dashOneThreshold: 1,
  dashTwoThreshold: 3,
  dashThreeThreshold: 5,
  showTime: true,
  timeIsoDisplay: "HH:mm:ss",
  showExcerpt: true,
  excerptLines: 2,
  noteSortBy: "creation-time",
  noteSortOrder: "ascending",
  weekStartDay: "sunday",
  weekNumberDisplay: "off",
  showSunday: true,
  showMonday: true,
  showTuesday: true,
  showWednesday: true,
  showThursday: true,
  showFriday: true,
  showSaturday: true
};
function normalizeTimeDisplayFormat(value) {
  const trimmed = value.trim();
  if (!trimmed) {
    return DEFAULT_SETTINGS.timeIsoDisplay;
  }
  return trimmed;
}
function normalizeWeekNumberDisplay(value) {
  if (value === "iso-8601" || value === "international") {
    return "iso-8601";
  }
  if (value === "united-states") {
    return "united-states";
  }
  return "off";
}
function normalizeExcerptLines(value) {
  if (value < 1) return 1;
  if (value > 5) return 5;
  return Math.round(value);
}
function normalizeNoteSortBy(value) {
  return value === "creation-time" ? "creation-time" : "name";
}
function normalizeSortOrder(value) {
  return value === "descending" ? "descending" : "ascending";
}
function normalizeWeekdayVisibility(settings) {
  WEEKDAY_VISIBILITY_KEYS.forEach((key) => {
    settings[key] = settings[key] !== false;
  });
  const hasVisibleDay = WEEKDAY_VISIBILITY_KEYS.some((key) => settings[key]);
  if (!hasVisibleDay) {
    WEEKDAY_VISIBILITY_KEYS.forEach((key) => {
      settings[key] = true;
    });
  }
}
function formatDateTime(date, format) {
  const padNumber = (value, width) => {
    const zeros = width === 3 ? "000" : "00";
    return (zeros + String(value)).slice(-width);
  };
  const year = date.getFullYear();
  const month = date.getMonth() + 1;
  const day = date.getDate();
  const hour24 = date.getHours();
  const hour12 = hour24 % 12 || 12;
  const minute = date.getMinutes();
  const second = date.getSeconds();
  const millisecond = date.getMilliseconds();
  const meridiem = hour24 >= 12 ? "PM" : "AM";
  const replacements = {
    "YYYY": String(year),
    "YY": String(year).slice(-2),
    "MM": padNumber(month, 2),
    "M": String(month),
    "DD": padNumber(day, 2),
    "D": String(day),
    "HH": padNumber(hour24, 2),
    "H": String(hour24),
    "hh": padNumber(hour12, 2),
    "h": String(hour12),
    "mm": padNumber(minute, 2),
    "m": String(minute),
    "ss": padNumber(second, 2),
    "s": String(second),
    "SSS": padNumber(millisecond, 3),
    "aa": meridiem,
    "a": meridiem.toLowerCase()
  };
  const tokenPattern = /(YYYY|YY|SSS|MM|M|DD|D|HH|H|hh|h|mm|m|ss|s|aa|a)/g;
  return format.replace(tokenPattern, (token) => {
    var _a;
    return (_a = replacements[token]) != null ? _a : token;
  });
}
var CalendarSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Note list").setHeading();
    new import_obsidian.Setting(containerEl).setName("Sort notes by").setDesc("Choose how notes are sorted in the note list.").addDropdown(
      (dropdown) => dropdown.addOption("name", "Name").addOption("creation-time", "Creation date/time").setValue(this.plugin.settings.noteSortBy).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.noteSortBy = normalizeNoteSortBy(value);
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Sort order").setDesc("Choose whether notes are shown ascending or descending.").addDropdown(
      (dropdown) => dropdown.addOption("ascending", "Ascending").addOption("descending", "Descending").setValue(this.plugin.settings.noteSortOrder).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.noteSortOrder = normalizeSortOrder(value);
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Show creation time").setDesc("Display note creation time.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showTime).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showTime = value;
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
        this.setSectionVisibility(timeFormatSection, value);
      }))
    );
    const timeFormatSection = containerEl.createDiv({ cls: "calendar-settings-nested-section" });
    const timeFormatSetting = new import_obsidian.Setting(timeFormatSection).setName("Time display format").setDesc(this.buildTimeFormatDesc(this.plugin.settings.timeIsoDisplay)).addText(
      (text) => text.setPlaceholder("HH:mm:ss").setValue(this.plugin.settings.timeIsoDisplay).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.timeIsoDisplay = normalizeTimeDisplayFormat(value);
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
        timeFormatSetting.setDesc(this.buildTimeFormatDesc(this.plugin.settings.timeIsoDisplay));
      }))
    );
    this.setSectionVisibility(timeFormatSection, this.plugin.settings.showTime);
    new import_obsidian.Setting(containerEl).setName("Show excerpt").setDesc("Display a short preview of each note's content.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showExcerpt).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showExcerpt = value;
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
        this.setSectionVisibility(excerptSection, value);
      }))
    );
    const excerptSection = containerEl.createDiv({ cls: "calendar-settings-nested-section" });
    new import_obsidian.Setting(excerptSection).setName("Excerpt lines").setDesc("Specify the maximum number of lines to show in note excerpts.").addDropdown(
      (dropdown) => dropdown.addOption("1", "1").addOption("2", "2").addOption("3", "3").addOption("4", "4").addOption("5", "5").setValue(String(this.plugin.settings.excerptLines)).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.excerptLines = normalizeExcerptLines(parseInt(value, 10));
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }))
    );
    this.setSectionVisibility(excerptSection, this.plugin.settings.showExcerpt);
    new import_obsidian.Setting(containerEl).setName("Calendar display").setHeading();
    new import_obsidian.Setting(containerEl).setName("Week starts on").setDesc("Choose the first day shown in each week.").addDropdown(
      (dropdown) => dropdown.addOption("sunday", "Sunday").addOption("monday", "Monday").setValue(this.plugin.settings.weekStartDay).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.weekStartDay = value === "monday" ? "monday" : "sunday";
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Week numbers").setDesc("Display week numbers in the calendar.").addDropdown(
      (dropdown) => dropdown.addOption("off", "Off").addOption("iso-8601", "ISO 8601").addOption("united-states", "United States").setValue(this.plugin.settings.weekNumberDisplay).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.weekNumberDisplay = normalizeWeekNumberDisplay(value);
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }))
    );
    const dayVisibilitySetting = new import_obsidian.Setting(containerEl).setName("Days to show").setDesc("Choose which weekdays are visible in the calendar.");
    dayVisibilitySetting.settingEl.addClass("calendar-days-setting");
    dayVisibilitySetting.controlEl.empty();
    const dayOptions = [
      { key: "showSunday", label: "Sunday", shortLabel: "Sun" },
      { key: "showMonday", label: "Monday", shortLabel: "Mon" },
      { key: "showTuesday", label: "Tuesday", shortLabel: "Tue" },
      { key: "showWednesday", label: "Wednesday", shortLabel: "Wed" },
      { key: "showThursday", label: "Thursday", shortLabel: "Thu" },
      { key: "showFriday", label: "Friday", shortLabel: "Fri" },
      { key: "showSaturday", label: "Saturday", shortLabel: "Sat" }
    ];
    const syncDayCheckboxes = (checkboxes) => {
      dayOptions.forEach(({ key }) => {
        const checkbox = checkboxes.get(key);
        if (checkbox) checkbox.checked = this.plugin.settings[key];
      });
    };
    const dayCheckboxContainer = dayVisibilitySetting.controlEl.createDiv({ cls: "calendar-days-checkboxes" });
    const dayCheckboxes = /* @__PURE__ */ new Map();
    dayOptions.forEach(({ key, label, shortLabel }) => {
      const option = dayCheckboxContainer.createEl("label", {
        cls: "calendar-days-checkbox-option",
        attr: { "aria-label": label, title: label }
      });
      const checkbox = option.createEl("input", {
        type: "checkbox",
        attr: { "aria-label": label }
      });
      checkbox.checked = this.plugin.settings[key];
      option.createSpan({ text: shortLabel });
      dayCheckboxes.set(key, checkbox);
      checkbox.onchange = () => __async(this, null, function* () {
        this.plugin.settings[key] = checkbox.checked;
        normalizeWeekdayVisibility(this.plugin.settings);
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
        syncDayCheckboxes(dayCheckboxes);
      });
    });
    new import_obsidian.Setting(containerEl).setName("Show note indicators").setDesc("Display indicators on days that have notes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showDashes).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showDashes = value;
        yield this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
        this.setSectionVisibility(thresholdSection, value);
      }))
    );
    const thresholdSection = containerEl.createDiv({ cls: "calendar-settings-nested-section" });
    this.setSectionVisibility(thresholdSection, this.plugin.settings.showDashes);
    thresholdSection.createEl("p", {
      text: "Set the minimum number of notes required for each indicator level.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(thresholdSection).setName("1 indicator").addText(
      (text) => text.setPlaceholder("1").setValue(String(this.plugin.settings.dashOneThreshold)).onChange((value) => __async(this, null, function* () {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 1) {
          this.plugin.settings.dashOneThreshold = num;
          yield this.plugin.saveSettings();
          this.plugin.refreshCalendarView();
        }
      }))
    );
    new import_obsidian.Setting(thresholdSection).setName("2 indicators").addText(
      (text) => text.setPlaceholder("3").setValue(String(this.plugin.settings.dashTwoThreshold)).onChange((value) => __async(this, null, function* () {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 1) {
          this.plugin.settings.dashTwoThreshold = num;
          yield this.plugin.saveSettings();
          this.plugin.refreshCalendarView();
        }
      }))
    );
    new import_obsidian.Setting(thresholdSection).setName("3 indicators").addText(
      (text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.dashThreeThreshold)).onChange((value) => __async(this, null, function* () {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 1) {
          this.plugin.settings.dashThreeThreshold = num;
          yield this.plugin.saveSettings();
          this.plugin.refreshCalendarView();
        }
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Create daily note on double-click/tap").setDesc("When enabled, double-clicking or double-tapping a date creates or opens that day's daily note. The Daily Notes core plugin is required.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableDailyNoteOnDoubleTap).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.enableDailyNoteOnDoubleTap = value;
        yield this.plugin.saveSettings();
      }))
    );
  }
  setSectionVisibility(section, visible) {
    section.classList.toggle("is-hidden", !visible);
  }
  buildTimeFormatDesc(format) {
    const now = /* @__PURE__ */ new Date();
    const preview = formatDateTime(now, format);
    return `Example: HH:mm, hh:mm:ss aa, YYYY-MM-DD. Preview: ${preview}`;
  }
};

// src/views/calendar-view.ts
var VIEW_TYPE_CALENDAR = "calendar-view";
var CalendarView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.selectedDate = null;
    this.selectedWeekStart = null;
    this.calendarContainer = null;
    this.notesContainer = null;
    this.monthDisplayContainer = null;
    this.monthDisplayButton = null;
    this.yearDisplayButton = null;
    this.headerSelectorPopover = null;
    this.activeHeaderSelector = null;
    this.modifyDebounceTimer = null;
    this.refreshGeneration = 0;
    this.lastTouchTapDateKey = null;
    this.lastTouchTapTimestamp = 0;
    this.plugin = plugin;
    this.currentDate = /* @__PURE__ */ new Date();
    this.selectedDate = new Date(this.currentDate.getFullYear(), this.currentDate.getMonth(), this.currentDate.getDate());
    this.yearSelectorCenter = this.currentDate.getFullYear();
  }
  getViewType() {
    return VIEW_TYPE_CALENDAR;
  }
  getDisplayText() {
    return "Calendar";
  }
  getIcon() {
    return "calendar-1";
  }
  onOpen() {
    var _a, _b;
    this.createCalendarView();
    const activeWindow = (_a = window.activeWindow) != null ? _a : window;
    const activeDocument = (_b = window.activeDocument) != null ? _b : document;
    this.registerEvent(this.app.vault.on("create", () => this.refresh()));
    this.registerEvent(this.app.vault.on("delete", () => this.refresh()));
    this.registerEvent(this.app.vault.on("rename", () => this.refresh()));
    this.registerEvent(this.app.vault.on("modify", () => {
      if (this.modifyDebounceTimer) activeWindow.clearTimeout(this.modifyDebounceTimer);
      this.modifyDebounceTimer = activeWindow.setTimeout(() => this.refresh(), 400);
    }));
    this.registerDomEvent(activeDocument, "click", (event) => {
      if (!this.activeHeaderSelector || !this.monthDisplayContainer) return;
      if (!this.monthDisplayContainer.contains(event.target)) {
        this.closeHeaderSelector();
      }
    });
    return Promise.resolve();
  }
  onClose() {
    var _a;
    if (this.modifyDebounceTimer) ((_a = window.activeWindow) != null ? _a : window).clearTimeout(this.modifyDebounceTimer);
    return Promise.resolve();
  }
  // Called by the plugin when settings change
  refresh() {
    this.refreshGeneration++;
    this.renderHeader();
    this.renderCalendar();
    this.updateNotesList();
    this.renderHeaderSelector();
  }
  createCalendarView() {
    const container = this.contentEl;
    container.empty();
    const mainContainer = container.createDiv("calendar-main-container");
    const header = mainContainer.createDiv("calendar-header");
    const todayButton = header.createEl("button", { attr: { "aria-label": "Go to today" } });
    todayButton.addClass("calendar-nav-button", "calendar-today-button");
    (0, import_obsidian2.setIcon)(todayButton, "calendar-1");
    todayButton.onclick = () => this.goToToday();
    this.monthDisplayContainer = header.createDiv("calendar-month-display");
    this.monthDisplayButton = this.monthDisplayContainer.createEl("button", { cls: "calendar-month-display-button" });
    this.monthDisplayButton.type = "button";
    this.monthDisplayButton.onclick = (event) => {
      event.stopPropagation();
      this.openMonthSelector();
    };
    this.yearDisplayButton = this.monthDisplayContainer.createEl("button", { cls: "calendar-month-display-button" });
    this.yearDisplayButton.type = "button";
    this.yearDisplayButton.onclick = (event) => {
      event.stopPropagation();
      this.openYearSelector();
    };
    this.renderHeader();
    const navGroup = header.createDiv("calendar-nav-group");
    const prevButton = navGroup.createEl("button", { text: "\u2190" });
    prevButton.addClass("calendar-nav-button");
    prevButton.onclick = () => this.previousMonth();
    const nextButton = navGroup.createEl("button", { text: "\u2192" });
    nextButton.addClass("calendar-nav-button");
    nextButton.onclick = () => this.nextMonth();
    this.calendarContainer = mainContainer.createDiv("calendar-grid-container");
    this.renderCalendar();
    this.notesContainer = mainContainer.createDiv("calendar-notes-container");
    this.updateNotesList();
  }
  renderCalendar() {
    var _a;
    if (!this.calendarContainer) return;
    const calendarContainer = this.calendarContainer;
    calendarContainer.empty();
    const showWeekNumbers = this.plugin.settings.weekNumberDisplay !== "off";
    const visibleWeekdays = this.getVisibleWeekdays();
    const visibleWeekdayCount = visibleWeekdays.length;
    calendarContainer.style.gridTemplateColumns = showWeekNumbers ? `auto repeat(${visibleWeekdayCount}, 1fr)` : `repeat(${visibleWeekdayCount}, 1fr)`;
    if (showWeekNumbers) {
      const weekLabel = calendarContainer.createDiv("calendar-week-label");
      weekLabel.setText(this.getQuarterLabel(this.currentDate));
    }
    visibleWeekdays.forEach(({ label }) => {
      const dayLabel = calendarContainer.createDiv("calendar-day-label");
      dayLabel.setText(label);
    });
    const year = this.currentDate.getFullYear();
    const month = this.currentDate.getMonth();
    const firstDay = this.getFirstDayOffset(new Date(year, month, 1).getDay());
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const totalWeeks = Math.ceil((firstDay + daysInMonth) / 7);
    const noteCountMap = this.buildNoteCountMap(year, month);
    for (let week = 0; week < totalWeeks; week++) {
      const weekStartDate = this.getCalendarRowStartDate(year, month, week, firstDay);
      if (showWeekNumbers) {
        const weekNumberCell = this.calendarContainer.createDiv("calendar-week-number");
        weekNumberCell.addClass("is-clickable");
        const weekNumberValue = weekNumberCell.createDiv("calendar-week-number-value");
        if (this.plugin.settings.showDashes) {
          weekNumberCell.createDiv("calendar-week-number-spacer");
        }
        if (this.selectedWeekStart && this.isSameDay(weekStartDate, this.selectedWeekStart)) {
          weekNumberCell.addClass("is-selected");
        }
        weekNumberValue.setText(String(this.getWeekNumberForRow(weekStartDate)));
        weekNumberCell.onclick = () => this.selectWeek(weekStartDate);
      }
      for (const weekday of visibleWeekdays) {
        const day = week * 7 + weekday.displayIndex - firstDay + 1;
        if (day < 1 || day > daysInMonth) {
          this.calendarContainer.createDiv("calendar-empty-day");
          continue;
        }
        const date = new Date(year, month, day);
        const dayCell = this.calendarContainer.createDiv("calendar-day");
        const dayNumber = dayCell.createDiv("calendar-day-number");
        dayNumber.setText(day.toString());
        if (this.plugin.settings.showDashes) {
          const noteCount = (_a = noteCountMap.get(day)) != null ? _a : 0;
          const dashCount = this.getDashCount(noteCount);
          const dashEl = dayCell.createDiv("calendar-day-dashes");
          for (let i = 0; i < dashCount; i++) {
            dashEl.createSpan("calendar-day-dash");
          }
        }
        dayCell.onclick = () => this.selectDate(date);
        dayCell.ondblclick = (event) => {
          event.preventDefault();
          void this.openOrCreateDailyNoteForDate(date);
        };
        dayCell.onpointerup = (event) => this.handleDayTouch(event, date);
        if (this.selectedWeekStart && this.isDateInWeek(date, this.selectedWeekStart)) {
          dayCell.addClass("calendar-day-in-selected-week");
        }
        if (this.selectedDate && this.isSameDay(date, this.selectedDate)) {
          dayCell.addClass("calendar-day-selected");
        }
      }
    }
  }
  getFirstDayOffset(day) {
    return this.plugin.settings.weekStartDay === "monday" ? (day + 6) % 7 : day;
  }
  getDaysOfWeek() {
    if (this.plugin.settings.weekStartDay === "monday") {
      return ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
    }
    return ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  }
  getVisibleWeekdays() {
    const orderedDays = this.getOrderedWeekdays();
    const visibleDays = orderedDays.filter(({ absoluteDay }) => this.isWeekdayVisible(absoluteDay));
    return visibleDays.length > 0 ? visibleDays : orderedDays;
  }
  getOrderedWeekdays() {
    if (this.plugin.settings.weekStartDay === "monday") {
      return [
        { label: "Mon", absoluteDay: 1, displayIndex: 0 },
        { label: "Tue", absoluteDay: 2, displayIndex: 1 },
        { label: "Wed", absoluteDay: 3, displayIndex: 2 },
        { label: "Thu", absoluteDay: 4, displayIndex: 3 },
        { label: "Fri", absoluteDay: 5, displayIndex: 4 },
        { label: "Sat", absoluteDay: 6, displayIndex: 5 },
        { label: "Sun", absoluteDay: 0, displayIndex: 6 }
      ];
    }
    return [
      { label: "Sun", absoluteDay: 0, displayIndex: 0 },
      { label: "Mon", absoluteDay: 1, displayIndex: 1 },
      { label: "Tue", absoluteDay: 2, displayIndex: 2 },
      { label: "Wed", absoluteDay: 3, displayIndex: 3 },
      { label: "Thu", absoluteDay: 4, displayIndex: 4 },
      { label: "Fri", absoluteDay: 5, displayIndex: 5 },
      { label: "Sat", absoluteDay: 6, displayIndex: 6 }
    ];
  }
  isWeekdayVisible(absoluteDay) {
    switch (absoluteDay) {
      case 0:
        return this.plugin.settings.showSunday;
      case 1:
        return this.plugin.settings.showMonday;
      case 2:
        return this.plugin.settings.showTuesday;
      case 3:
        return this.plugin.settings.showWednesday;
      case 4:
        return this.plugin.settings.showThursday;
      case 5:
        return this.plugin.settings.showFriday;
      case 6:
        return this.plugin.settings.showSaturday;
      default:
        return true;
    }
  }
  getWeekNumber(date) {
    if (this.plugin.settings.weekNumberDisplay === "iso-8601") {
      return this.getIsoWeekNumber(date);
    }
    return this.getUnitedStatesWeekNumber(date);
  }
  getWeekNumberForRow(weekStartDate) {
    return this.getWeekNumber(this.getDisplayedWeekAnchorDate(weekStartDate));
  }
  getDisplayedWeekAnchorDate(weekStartDate) {
    const offset = this.plugin.settings.weekStartDay === "monday" ? 3 : 4;
    return new Date(
      weekStartDate.getFullYear(),
      weekStartDate.getMonth(),
      weekStartDate.getDate() + offset
    );
  }
  getIsoWeekNumber(date) {
    const utcDate = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
    const dayNumber = utcDate.getUTCDay() || 7;
    utcDate.setUTCDate(utcDate.getUTCDate() + 4 - dayNumber);
    const yearStart = new Date(Date.UTC(utcDate.getUTCFullYear(), 0, 1));
    return Math.ceil(((utcDate.getTime() - yearStart.getTime()) / 864e5 + 1) / 7);
  }
  getUnitedStatesWeekNumber(date) {
    const normalized = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    const yearStart = new Date(normalized.getFullYear(), 0, 1);
    const dayOfYear = Math.floor((normalized.getTime() - yearStart.getTime()) / 864e5);
    const jan1Day = yearStart.getDay();
    return Math.floor((dayOfYear + jan1Day) / 7) + 1;
  }
  selectDate(date) {
    this.selectedDate = date;
    this.selectedWeekStart = null;
    this.renderCalendar();
    this.updateNotesList();
  }
  selectWeek(weekStartDate) {
    this.selectedWeekStart = new Date(
      weekStartDate.getFullYear(),
      weekStartDate.getMonth(),
      weekStartDate.getDate()
    );
    this.selectedDate = null;
    this.renderCalendar();
    this.updateNotesList();
  }
  previousMonth() {
    this.closeHeaderSelector();
    this.currentDate = new Date(
      this.currentDate.getFullYear(),
      this.currentDate.getMonth() - 1,
      1
    );
    this.yearSelectorCenter = this.currentDate.getFullYear();
    this.renderHeader();
    this.renderCalendar();
    this.updateNotesList();
  }
  goToToday() {
    this.closeHeaderSelector();
    const now = /* @__PURE__ */ new Date();
    this.currentDate = new Date(now.getFullYear(), now.getMonth(), 1);
    this.selectedDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    this.selectedWeekStart = null;
    this.yearSelectorCenter = now.getFullYear();
    this.renderHeader();
    this.renderCalendar();
    this.updateNotesList();
  }
  nextMonth() {
    this.closeHeaderSelector();
    this.currentDate = new Date(
      this.currentDate.getFullYear(),
      this.currentDate.getMonth() + 1,
      1
    );
    this.yearSelectorCenter = this.currentDate.getFullYear();
    this.renderHeader();
    this.renderCalendar();
    this.updateNotesList();
  }
  renderHeader() {
    if (!this.monthDisplayButton || !this.yearDisplayButton) return;
    this.monthDisplayButton.setText(this.getMonthName(this.currentDate.getMonth()));
    this.yearDisplayButton.setText(String(this.currentDate.getFullYear()));
  }
  openMonthSelector() {
    this.activeHeaderSelector = this.activeHeaderSelector === "month" ? null : "month";
    this.renderHeaderSelector();
  }
  openYearSelector() {
    if (this.activeHeaderSelector === "year") {
      this.closeHeaderSelector();
      return;
    }
    this.yearSelectorCenter = this.currentDate.getFullYear();
    this.activeHeaderSelector = "year";
    this.renderHeaderSelector();
  }
  renderHeaderSelector() {
    if (!this.monthDisplayContainer) return;
    if (this.headerSelectorPopover) {
      this.headerSelectorPopover.remove();
      this.headerSelectorPopover = null;
    }
    if (!this.activeHeaderSelector) return;
    const popover = this.monthDisplayContainer.createDiv("calendar-header-popover");
    popover.onclick = (event) => event.stopPropagation();
    this.headerSelectorPopover = popover;
    if (this.activeHeaderSelector === "month") {
      this.renderMonthSelector(popover);
      return;
    }
    this.renderYearSelector(popover);
  }
  renderMonthSelector(popover) {
    const grid = popover.createDiv("calendar-header-selector-grid");
    const shortNames = [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ];
    shortNames.forEach((month, index) => {
      const button = grid.createEl("button", {
        cls: "calendar-header-selector-option",
        text: month
      });
      button.type = "button";
      if (index === this.currentDate.getMonth()) {
        button.addClass("is-selected");
      }
      button.onclick = () => {
        this.currentDate = new Date(this.currentDate.getFullYear(), index, 1);
        this.renderHeader();
        this.renderCalendar();
        this.updateNotesList();
        this.closeHeaderSelector();
      };
    });
  }
  renderYearSelector(popover) {
    const nav = popover.createDiv("calendar-header-selector-nav");
    const previousButton = nav.createEl("button", {
      cls: "calendar-header-selector-nav-button",
      text: "\u2190"
    });
    previousButton.type = "button";
    previousButton.onclick = () => {
      this.yearSelectorCenter -= 9;
      this.renderHeaderSelector();
    };
    const rangeLabel = nav.createDiv("calendar-header-selector-range");
    rangeLabel.setText(`${this.yearSelectorCenter - 4} - ${this.yearSelectorCenter + 4}`);
    const nextButton = nav.createEl("button", {
      cls: "calendar-header-selector-nav-button",
      text: "\u2192"
    });
    nextButton.type = "button";
    nextButton.onclick = () => {
      this.yearSelectorCenter += 9;
      this.renderHeaderSelector();
    };
    const grid = popover.createDiv("calendar-header-selector-grid");
    for (let year = this.yearSelectorCenter - 4; year <= this.yearSelectorCenter + 4; year++) {
      const button = grid.createEl("button", {
        cls: "calendar-header-selector-option",
        text: String(year)
      });
      button.type = "button";
      if (year === this.currentDate.getFullYear()) {
        button.addClass("is-selected");
      }
      button.onclick = () => {
        this.currentDate = new Date(year, this.currentDate.getMonth(), 1);
        this.renderHeader();
        this.renderCalendar();
        this.updateNotesList();
        this.closeHeaderSelector();
      };
    }
  }
  closeHeaderSelector() {
    this.activeHeaderSelector = null;
    if (!this.headerSelectorPopover) return;
    this.headerSelectorPopover.remove();
    this.headerSelectorPopover = null;
  }
  updateNotesList() {
    const selectedDate = this.selectedDate;
    const selectedWeekStart = this.selectedWeekStart;
    if (!this.notesContainer || !selectedDate && !selectedWeekStart) {
      if (this.notesContainer) {
        this.notesContainer.empty();
        const emptyMsg = this.notesContainer.createDiv("calendar-notes-empty");
        emptyMsg.setText("Select a date or week to view notes");
      }
      return;
    }
    this.notesContainer.empty();
    let notes;
    if (selectedWeekStart) {
      notes = this.getNotesForWeek(selectedWeekStart);
    } else if (selectedDate) {
      notes = this.getNotesForDate(selectedDate);
    } else {
      return;
    }
    if (notes.length === 0) {
      const emptyMsg = this.notesContainer.createDiv("calendar-notes-empty");
      if (selectedWeekStart) {
        emptyMsg.setText(`No notes for ${this.getWeekLabel(selectedWeekStart)}`);
      } else if (selectedDate) {
        emptyMsg.setText(`No notes for ${this.formatDate(selectedDate)}`);
      } else {
        emptyMsg.setText("No notes found");
      }
      return;
    }
    const notesList = this.notesContainer.createDiv("calendar-notes-list");
    notes.forEach((note) => {
      const noteItem = notesList.createDiv("calendar-note-item");
      noteItem.onclick = () => {
        void this.app.workspace.getLeaf(false).openFile(note);
      };
      if (this.plugin.settings.showTime) {
        const createdTime = new Date(note.stat.ctime);
        const timeEl = noteItem.createDiv("calendar-note-time");
        timeEl.setText(formatDateTime(createdTime, this.plugin.settings.timeIsoDisplay));
      }
      const noteLink = noteItem.createDiv("calendar-note-name");
      noteLink.setText(note.basename || note.name);
      if (this.plugin.settings.showExcerpt) {
        const excerptEl = noteItem.createDiv("calendar-note-excerpt");
        excerptEl.addClass(`calendar-note-excerpt-lines-${this.plugin.settings.excerptLines}`);
        excerptEl.setText("...");
        const generation = this.refreshGeneration;
        void this.populateExcerpt(note, excerptEl, generation);
      }
    });
  }
  populateExcerpt(note, excerptEl, generation) {
    return __async(this, null, function* () {
      try {
        const content = yield this.app.vault.cachedRead(note);
        if (this.refreshGeneration !== generation) {
          return;
        }
        excerptEl.setText(this.createExcerptText(content) || "\u2014");
      } catch (e) {
        if (this.refreshGeneration === generation) {
          excerptEl.setText("\u2014");
        }
      }
    });
  }
  createExcerptText(content) {
    return content.replace(/^---[\s\S]*?---\n?/, "").replace(/#+\s+.*/g, "").replace(/[[\]*_`]/g, "").replace(/\s+/g, " ").trim();
  }
  getNotesForDate(date) {
    const notes = [];
    this.app.vault.getMarkdownFiles().forEach((file) => {
      if (this.isNoteCreatedOnDate(file, date)) {
        notes.push(file);
      }
    });
    return this.sortNotes(notes);
  }
  getNotesForWeek(weekStartDate) {
    const notes = [];
    this.app.vault.getMarkdownFiles().forEach((file) => {
      if (this.isNoteCreatedInWeek(file, weekStartDate)) {
        notes.push(file);
      }
    });
    return this.sortNotes(notes);
  }
  sortNotes(notes) {
    const direction = this.plugin.settings.noteSortOrder === "ascending" ? 1 : -1;
    return notes.sort((left, right) => {
      if (this.plugin.settings.noteSortBy === "creation-time") {
        const timeDifference = left.stat.ctime - right.stat.ctime;
        if (timeDifference !== 0) {
          return timeDifference * direction;
        }
      }
      const nameDifference = left.basename.localeCompare(right.basename);
      if (nameDifference !== 0) {
        return nameDifference * direction;
      }
      return (left.stat.ctime - right.stat.ctime) * direction;
    });
  }
  buildNoteCountMap(year, month) {
    const map = /* @__PURE__ */ new Map();
    this.app.vault.getMarkdownFiles().forEach((file) => {
      var _a;
      const fileDate = new Date(file.stat.ctime);
      if (fileDate.getFullYear() === year && fileDate.getMonth() === month) {
        const day = fileDate.getDate();
        map.set(day, ((_a = map.get(day)) != null ? _a : 0) + 1);
      }
    });
    return map;
  }
  getDashCount(noteCount) {
    const { dashOneThreshold, dashTwoThreshold, dashThreeThreshold } = this.plugin.settings;
    if (noteCount >= dashThreeThreshold) return 3;
    if (noteCount >= dashTwoThreshold) return 2;
    if (noteCount >= dashOneThreshold) return 1;
    return 0;
  }
  isNoteCreatedOnDate(file, date) {
    const fileDate = new Date(file.stat.ctime);
    return this.isSameDay(fileDate, date);
  }
  isNoteCreatedInWeek(file, weekStartDate) {
    const fileDate = new Date(file.stat.ctime);
    return this.isDateInWeek(fileDate, weekStartDate);
  }
  isSameDay(date1, date2) {
    return date1.getDate() === date2.getDate() && date1.getMonth() === date2.getMonth() && date1.getFullYear() === date2.getFullYear();
  }
  formatDate(date) {
    const pad = (n) => ("0" + String(n)).slice(-2);
    const year = date.getFullYear();
    return `${year}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
  }
  getQuarterLabel(date) {
    return `Q${Math.floor(date.getMonth() / 3) + 1}`;
  }
  getCalendarRowStartDate(year, month, week, firstDayOffset) {
    return new Date(year, month, week * 7 - firstDayOffset + 1);
  }
  getWeekEndDate(weekStartDate) {
    return new Date(weekStartDate.getFullYear(), weekStartDate.getMonth(), weekStartDate.getDate() + 6);
  }
  isDateInWeek(date, weekStartDate) {
    const weekEndDate = this.getWeekEndDate(weekStartDate);
    const normalizedDate = new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime();
    const normalizedStart = new Date(weekStartDate.getFullYear(), weekStartDate.getMonth(), weekStartDate.getDate()).getTime();
    const normalizedEnd = new Date(weekEndDate.getFullYear(), weekEndDate.getMonth(), weekEndDate.getDate()).getTime();
    return normalizedDate >= normalizedStart && normalizedDate <= normalizedEnd;
  }
  getWeekLabel(weekStartDate) {
    const weekEndDate = this.getWeekEndDate(weekStartDate);
    return `week ${this.getWeekNumberForRow(weekStartDate)} (${this.formatDate(weekStartDate)} to ${this.formatDate(weekEndDate)})`;
  }
  getMonthName(month) {
    var _a;
    return (_a = this.getMonthNames()[month]) != null ? _a : "";
  }
  getMonthNames() {
    return [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ];
  }
  handleDayTouch(event, date) {
    if (event.pointerType !== "touch") {
      return;
    }
    const currentTapDateKey = this.formatDate(date);
    const now = Date.now();
    const isDoubleTap = this.lastTouchTapDateKey === currentTapDateKey && now - this.lastTouchTapTimestamp <= 350;
    this.lastTouchTapDateKey = currentTapDateKey;
    this.lastTouchTapTimestamp = now;
    if (!isDoubleTap) {
      return;
    }
    this.lastTouchTapDateKey = null;
    this.lastTouchTapTimestamp = 0;
    void this.openOrCreateDailyNoteForDate(date);
  }
  openOrCreateDailyNoteForDate(date) {
    return __async(this, null, function* () {
      if (!this.plugin.settings.enableDailyNoteOnDoubleTap) {
        return;
      }
      const dailyNotesSettings = this.getDailyNotesCoreSettings();
      if (!dailyNotesSettings.enabled) {
        new import_obsidian2.Notice("Enable the Daily notes core plugin to create daily notes from the calendar.");
        return;
      }
      const fileName = `${this.formatWithMoment(date, dailyNotesSettings.format)}.md`;
      const notePath = (0, import_obsidian2.normalizePath)(
        dailyNotesSettings.folder ? `${dailyNotesSettings.folder}/${fileName}` : fileName
      );
      try {
        const existingFile = this.app.vault.getAbstractFileByPath(notePath);
        if (existingFile instanceof import_obsidian2.TFile) {
          yield this.app.workspace.getLeaf(false).openFile(existingFile);
          return;
        }
        if (existingFile) {
          new import_obsidian2.Notice(`Unable to create daily note. A folder exists at ${notePath}.`);
          return;
        }
        yield this.ensureParentFolderExists(notePath);
        const templateContent = yield this.readDailyNoteTemplate(dailyNotesSettings.template);
        const renderedTemplate = this.renderCoreTemplate(
          templateContent,
          date,
          fileName.replace(/\.md$/i, ""),
          dailyNotesSettings.format
        );
        const timestamp = this.getDailyNoteTimestamp(date);
        const createdFile = yield this.app.vault.create(notePath, renderedTemplate, {
          ctime: timestamp,
          mtime: timestamp
        });
        yield this.app.workspace.getLeaf(false).openFile(createdFile);
      } catch (error) {
        console.error("Failed to create daily note from calendar:", error);
        new import_obsidian2.Notice(`Could not create daily note for ${this.formatDate(date)}.`);
      }
    });
  }
  getDailyNotesCoreSettings() {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const appWithInternalPlugins = this.app;
    const plugin = (_e = (_b = (_a = appWithInternalPlugins.internalPlugins) == null ? void 0 : _a.getPluginById) == null ? void 0 : _b.call(_a, "daily-notes")) != null ? _e : (_d = (_c = appWithInternalPlugins.internalPlugins) == null ? void 0 : _c.plugins) == null ? void 0 : _d["daily-notes"];
    const instanceCandidate = plugin == null ? void 0 : plugin.instance;
    const optionsCandidate = (_h = (_g = (_f = plugin == null ? void 0 : plugin.instance) == null ? void 0 : _f.options) != null ? _g : instanceCandidate) != null ? _h : {};
    const folder = this.readDailyNotesOption(optionsCandidate.folder);
    const format = this.readDailyNotesOption(optionsCandidate.format).length > 0 ? this.readDailyNotesOption(optionsCandidate.format) : "YYYY-MM-DD";
    const template = this.readDailyNotesOption(optionsCandidate.template) || this.readDailyNotesOption(optionsCandidate.templatePath) || this.readDailyNotesOption(optionsCandidate.template_file) || this.readDailyNotesOption(optionsCandidate.templateFile);
    return {
      enabled: (plugin == null ? void 0 : plugin.enabled) === true,
      folder,
      format,
      template
    };
  }
  ensureParentFolderExists(filePath) {
    return __async(this, null, function* () {
      const segments = filePath.split("/");
      if (segments.length <= 1) {
        return;
      }
      segments.pop();
      let currentPath = "";
      for (const segment of segments) {
        currentPath = currentPath ? `${currentPath}/${segment}` : segment;
        const existing = this.app.vault.getAbstractFileByPath(currentPath);
        if (!existing) {
          yield this.app.vault.createFolder(currentPath);
          continue;
        }
        if (!(existing instanceof import_obsidian2.TFolder)) {
          throw new Error(`Cannot create folder ${currentPath} because a file already exists at this path.`);
        }
      }
    });
  }
  readDailyNoteTemplate(templatePath) {
    return __async(this, null, function* () {
      if (!templatePath) {
        return "";
      }
      const templateFile = this.resolveDailyTemplateFile(templatePath);
      if (!templateFile) return "";
      try {
        return yield this.app.vault.cachedRead(templateFile);
      } catch (e) {
        return "";
      }
    });
  }
  resolveDailyTemplateFile(templatePath) {
    var _a;
    const trimmed = templatePath.trim();
    if (!trimmed) return null;
    const candidates = /* @__PURE__ */ new Set();
    candidates.add((0, import_obsidian2.normalizePath)(trimmed));
    candidates.add((0, import_obsidian2.normalizePath)(trimmed.replace(/^\/+/, "")));
    if (!/\.md$/i.test(trimmed)) {
      candidates.add((0, import_obsidian2.normalizePath)(`${trimmed}.md`));
      candidates.add((0, import_obsidian2.normalizePath)(`${trimmed.replace(/^\/+/, "")}.md`));
    }
    for (const candidate of candidates) {
      const file = this.app.vault.getAbstractFileByPath(candidate);
      if (file instanceof import_obsidian2.TFile) {
        return file;
      }
    }
    const wantedPath = (0, import_obsidian2.normalizePath)(trimmed).replace(/\.md$/i, "").toLowerCase();
    return (_a = this.app.vault.getMarkdownFiles().find((file) => {
      const filePathNoExtension = file.path.replace(/\.md$/i, "").toLowerCase();
      return filePathNoExtension === wantedPath || file.basename.toLowerCase() === wantedPath;
    })) != null ? _a : null;
  }
  renderCoreTemplate(template, date, title, dateFormat) {
    if (!template) {
      return "";
    }
    return template.replace(/{{\s*(date|time|title)(?::([^}]+))?\s*}}/gi, (_match, token, format) => {
      const normalizedToken = token.toLowerCase();
      if (normalizedToken === "title") {
        return title;
      }
      const tokenFormat = (format != null ? format : "").trim();
      if (normalizedToken === "date") {
        return this.formatWithMoment(date, tokenFormat || dateFormat || "YYYY-MM-DD");
      }
      const timeSource = new Date(date.getFullYear(), date.getMonth(), date.getDate());
      return this.formatWithMoment(timeSource, tokenFormat || "HH:mm");
    });
  }
  readDailyNotesOption(value) {
    return typeof value === "string" ? value.trim() : "";
  }
  formatWithMoment(date, format) {
    const momentFormatter = import_obsidian2.moment;
    return momentFormatter(date).format(format);
  }
  getDailyNoteTimestamp(date) {
    return new Date(date.getFullYear(), date.getMonth(), date.getDate(), 12, 0, 0, 0).getTime();
  }
};

// src/main.ts
var CalendarPlugin = class extends import_obsidian3.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.registerView(
        VIEW_TYPE_CALENDAR,
        (leaf) => new CalendarView(leaf, this)
      );
      this.addSettingTab(new CalendarSettingTab(this.app, this));
      this.addRibbonIcon("calendar-glyph", "Open calendar", () => __async(this, null, function* () {
        yield this.activateView();
      }));
      this.addCommand({
        id: "open-calendar",
        name: "Open calendar",
        callback: () => __async(this, null, function* () {
          yield this.activateView();
        })
      });
      this.app.workspace.onLayoutReady(() => {
        void this.activateView();
      });
    });
  }
  onunload() {
  }
  loadSettings() {
    return __async(this, null, function* () {
      var _a, _b, _c, _d, _e;
      const loadedData = yield this.loadData();
      const parsedData = loadedData != null ? loadedData : {};
      this.settings = Object.assign({}, DEFAULT_SETTINGS, parsedData);
      this.settings.enableDailyNoteOnDoubleTap = this.settings.enableDailyNoteOnDoubleTap !== false;
      this.settings.timeIsoDisplay = normalizeTimeDisplayFormat((_a = this.settings.timeIsoDisplay) != null ? _a : "");
      this.settings.excerptLines = normalizeExcerptLines((_b = this.settings.excerptLines) != null ? _b : DEFAULT_SETTINGS.excerptLines);
      this.settings.noteSortBy = normalizeNoteSortBy((_c = this.settings.noteSortBy) != null ? _c : "");
      this.settings.noteSortOrder = normalizeSortOrder((_d = this.settings.noteSortOrder) != null ? _d : "");
      this.settings.weekNumberDisplay = normalizeWeekNumberDisplay((_e = this.settings.weekNumberDisplay) != null ? _e : "");
      normalizeWeekdayVisibility(this.settings);
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  refreshCalendarView() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_CALENDAR).forEach((leaf) => {
      if (leaf.view instanceof CalendarView) {
        leaf.view.refresh();
      }
    });
  }
  activateView() {
    return __async(this, null, function* () {
      try {
        const { workspace } = this.app;
        let leaf = null;
        const leaves = workspace.getLeavesOfType(VIEW_TYPE_CALENDAR);
        if (leaves.length > 0) {
          leaf = leaves[0];
        } else {
          leaf = workspace.getRightLeaf(false);
          if (leaf) {
            yield leaf.setViewState({ type: VIEW_TYPE_CALENDAR, active: true });
          }
        }
        if (leaf) {
          workspace.setActiveLeaf(leaf, { focus: false });
        }
      } catch (error) {
        console.error("Failed to activate calendar view:", error);
      }
    });
  }
};

/* nosourcemap */