#
# Varmilo keyboard, replace all `Super` to `Alt`
# DygmaRise keyboard, replace all `Alt` to `Super`
#
[colors]
draw_bold_text_with_bright_colors = true

# [colors.primary]
# foreground = "#9DE2DD"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
chars = """
clear
"""
key = "K"
mods = "Super"

[[keyboard.bindings]]
chars = "/opt/homebrew/bin/tmux rename-window "
key = "I"
mods = "Super"

[[keyboard.bindings]]
key = "T"
mods = "Super"

[keyboard.bindings.command]
args = ["new-window"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "W"
mods = "Super"

[keyboard.bindings.command]
args = ["kill-window"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "H"
mods = "Super"

[keyboard.bindings.command]
args = ["prev"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "L"
mods = "Super"

[keyboard.bindings.command]
args = ["next"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "H"
mods = "Super|Shift"

[keyboard.bindings.command]
args = ["-C", "/opt/homebrew/bin/tmux swap-window -t -1 && /opt/homebrew/bin/tmux previous-window"]
program = "/usr/bin/fish"

[[keyboard.bindings]]
key = "L"
mods = "Super|Shift"

[keyboard.bindings.command]
args = ["-C", "/opt/homebrew/bin/tmux swap-window -t +1 && /opt/homebrew/bin/tmux next-window"]
program = "/usr/bin/fish"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-C", "/opt/homebrew/bin/tmux switch-client -n"]
program = "/usr/bin/fish"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-C", "/opt/homebrew/bin/tmux switch-client -p"]
program = "/usr/bin/fish"

[window]
# decorations = "none"
opacity = 0.95
# startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
