#
# Varmilo keyboard, replace all `Super` to `Alt`
# DygmaRise keyboard, replace all `Alt` to `Super`
#

import = ["/home/fion/.cache/wal/colors-alacritty.toml"]

[colors]
draw_bold_text_with_bright_colors = true

# [colors.primary]
# foreground = "#9DE2DD"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
key = "Key1"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 1"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "Key2"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 2"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "Key3"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 3"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "Key4"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 4"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "Key5"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 5"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "Key6"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 6"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "Key7"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 7"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "Key8"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 8"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "Key9"
mods = "Super"

[keyboard.bindings.command]
args = ["select-window", "-t 9"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
chars = """
clear
"""
key = "K"
mods = "Super"

[[keyboard.bindings]]
chars = "tmux rename-window "
key = "I"
mods = "Super"

[[keyboard.bindings]]
key = "T"
mods = "Super"

[keyboard.bindings.command]
args = ["new-window"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "W"
mods = "Super"

[keyboard.bindings.command]
args = ["kill-window"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "H"
mods = "Super"

[keyboard.bindings.command]
args = ["prev"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "L"
mods = "Super"

[keyboard.bindings.command]
args = ["next"]
program = "/usr/bin/tmux"

[[keyboard.bindings]]
key = "H"
mods = "Super|Shift"

[keyboard.bindings.command]
args = ["-C", "/usr/bin/tmux swap-window -t -1 && /usr/bin/tmux previous-window"]
program = "/usr/bin/fish"

[[keyboard.bindings]]
key = "L"
mods = "Super|Shift"

[keyboard.bindings.command]
args = ["-C", "/usr/bin/tmux swap-window -t +1 && /usr/bin/tmux next-window"]
program = "/usr/bin/fish"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-C", "/usr/bin/tmux switch-client -n"]
program = "/usr/bin/fish"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-C", "/usr/bin/tmux switch-client -p"]
program = "/usr/bin/fish"

[window]
decorations = "none"
# opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
