set --export foreground {foreground.strip}
set --export background {background.strip}
set --export color0 {color0.strip}
set --export color1 {color1.strip}
set --export color2 {color2.strip}
set --export color3 {color3.strip}
set --export color4 {color4.strip}
set --export color5 {color5.strip}
set --export color6 {color6.strip}
set --export color7 {color7.strip}
set --export color8 {color8.strip}
set --export color9 {color9.strip}
set --export color10 {color10.strip}
set --export color11 {color11.strip}
set --export color12 {color12.strip}
set --export color13 {color13.strip}
set --export color14 {color14.strip}
set --export color15 {color15.strip}
