confirm_os_window_close 0

# Fonts
font_family         JetBrainsMonoNerdFont
bold_font           auto
italic_font         auto
bold_italic_font    auto
font_size           16


# Misc
scrollback_lines    5000
scrollbar           never


# UI
background_opacity  0.9

# Layouts
enabled_layouts     Tall,stack

window_padding_width    10
window_border_width     1

# Tab
tab_bar_edge            bottom
tab_bar_align           center
tab_bar_min_tabs        1
tab_title_max_length    40
tab_bar_margin_height   40
tab_bar_style           slant

# Keybinding
kitty_mode              ctrl+shift

# change font size
map ctrl+minus change_font_size all -2.0
map ctrl+equal change_font_size all +2.0

# Scrolling way
map alt+n scroll_line_up
map alt+m scroll_line_down

# split windows
map alt+t new_window
map alt+w close_window
map alt+i set_window_title
map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+j neighboring_window bottom
map alt+k neighboring_window top

# toggle the stack layout
map alt+z toggle_layout stack

# resize window
map alt+r start_resizing_window

map ctrl+shift+space launch --stdin-source=@screen_scrollback --type=overlay nvim +"set nospell" -
